theme: jekyll-theme-cayman
title: Rebecca Clements
description: Biomedical Engineering Student at the University of Delaware
author :
  email : rclement@udel.edu
[LinkedIn](https://www.linkedin.com/in/rebeccaclements1/)
